services:
  - type: web
    name: aplikasi-sistem-manajemen
    env: php
    buildCommand: |
      composer install --ignore-platform-reqs
      php artisan key:generate
      php artisan migrate --force
      npm install
      npm run build
    startCommand: php artisan serve --host=0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://aplikasi-sistem-manajemen.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false

